const mockProducts = [
  {
    _id: "1",
    name: "Air Flex Runner",
    brand: "Nike",
    price: 129.99,
    rating: 4.6,
    reviewCount: 184,
    category: "sports",
    description:
      "Lightweight running shoes designed for speed, comfort, and breathability.",
    images: [
      "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
      "https://images.unsplash.com/photo-1600185365926-3c2c49d0d0c9",
    ],
    colors: ["black", "white", "red"],
    sizes: [7, 8, 9, 10, 11],
    inStock: true,
    stockCount: 20,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "2",
    name: "Urban Street Classic",
    brand: "Adidas",
    price: 99.5,
    rating: 4.3,
    reviewCount: 98,
    category: "casual",
    description:
      "Everyday sneakers with a clean silhouette and all-day comfort.",
    images: [
      "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77",
      "https://images.unsplash.com/photo-1549298916-b41d501d3772",
    ],
    colors: ["white", "gray"],
    sizes: [6, 7, 8, 9, 10],
    inStock: true,
    stockCount: 15,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "3",
    name: "Velocity Pro",
    brand: "Puma",
    price: 149.0,
    rating: 4.8,
    reviewCount: 212,
    category: "men",
    description:
      "High-performance training shoes built for durability and stability.",
    images: [
      "https://images.unsplash.com/photo-1585386959984-a4155224a1ad",
      "https://images.unsplash.com/photo-1608231387042-66d1773070a5",
    ],
    colors: ["blue", "black"],
    sizes: [8, 9, 10, 11, 12],
    inStock: true,
    stockCount: 8,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "4",
    name: "Mini Sprint",
    brand: "Reebok",
    price: 69.99,
    rating: 4.1,
    reviewCount: 45,
    category: "kids",
    description:
      "Comfortable and durable shoes made especially for kids’ active days.",
    images: ["https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a"],
    colors: ["pink", "blue"],
    sizes: [1, 2, 3, 4, 5],
    inStock: true,
    stockCount: 25,
    createdAt: new Date().toISOString(),
  },
];

export default mockProducts;
